# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import archimedes_pb2 as archimedes__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in archimedes_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoherenceAgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SimulateSU2 = channel.unary_unary(
                '/archimedes.CoherenceAgent/SimulateSU2',
                request_serializer=archimedes__pb2.SU2Request.SerializeToString,
                response_deserializer=archimedes__pb2.CoherenceResponse.FromString,
                _registered_method=True)
        self.SimulateSL3Z = channel.unary_unary(
                '/archimedes.CoherenceAgent/SimulateSL3Z',
                request_serializer=archimedes__pb2.SL3ZRequest.SerializeToString,
                response_deserializer=archimedes__pb2.CoherenceResponse.FromString,
                _registered_method=True)
        self.DetectPeaks = channel.unary_unary(
                '/archimedes.CoherenceAgent/DetectPeaks',
                request_serializer=archimedes__pb2.PeakDetectionRequest.SerializeToString,
                response_deserializer=archimedes__pb2.PeakDetectionResponse.FromString,
                _registered_method=True)
        self.Analyze = channel.unary_unary(
                '/archimedes.CoherenceAgent/Analyze',
                request_serializer=archimedes__pb2.AnalysisRequest.SerializeToString,
                response_deserializer=archimedes__pb2.AnalysisResponse.FromString,
                _registered_method=True)
        self.StreamCoherence = channel.stream_stream(
                '/archimedes.CoherenceAgent/StreamCoherence',
                request_serializer=archimedes__pb2.CoherenceStreamRequest.SerializeToString,
                response_deserializer=archimedes__pb2.CoherenceStreamResponse.FromString,
                _registered_method=True)


class CoherenceAgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SimulateSU2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimulateSL3Z(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectPeaks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Analyze(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCoherence(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoherenceAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SimulateSU2': grpc.unary_unary_rpc_method_handler(
                    servicer.SimulateSU2,
                    request_deserializer=archimedes__pb2.SU2Request.FromString,
                    response_serializer=archimedes__pb2.CoherenceResponse.SerializeToString,
            ),
            'SimulateSL3Z': grpc.unary_unary_rpc_method_handler(
                    servicer.SimulateSL3Z,
                    request_deserializer=archimedes__pb2.SL3ZRequest.FromString,
                    response_serializer=archimedes__pb2.CoherenceResponse.SerializeToString,
            ),
            'DetectPeaks': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectPeaks,
                    request_deserializer=archimedes__pb2.PeakDetectionRequest.FromString,
                    response_serializer=archimedes__pb2.PeakDetectionResponse.SerializeToString,
            ),
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=archimedes__pb2.AnalysisRequest.FromString,
                    response_serializer=archimedes__pb2.AnalysisResponse.SerializeToString,
            ),
            'StreamCoherence': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamCoherence,
                    request_deserializer=archimedes__pb2.CoherenceStreamRequest.FromString,
                    response_serializer=archimedes__pb2.CoherenceStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'archimedes.CoherenceAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('archimedes.CoherenceAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoherenceAgent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SimulateSU2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/archimedes.CoherenceAgent/SimulateSU2',
            archimedes__pb2.SU2Request.SerializeToString,
            archimedes__pb2.CoherenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SimulateSL3Z(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/archimedes.CoherenceAgent/SimulateSL3Z',
            archimedes__pb2.SL3ZRequest.SerializeToString,
            archimedes__pb2.CoherenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectPeaks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/archimedes.CoherenceAgent/DetectPeaks',
            archimedes__pb2.PeakDetectionRequest.SerializeToString,
            archimedes__pb2.PeakDetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/archimedes.CoherenceAgent/Analyze',
            archimedes__pb2.AnalysisRequest.SerializeToString,
            archimedes__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCoherence(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/archimedes.CoherenceAgent/StreamCoherence',
            archimedes__pb2.CoherenceStreamRequest.SerializeToString,
            archimedes__pb2.CoherenceStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
