import numpy as np
import os

def export():
    os.makedirs('exports', exist_ok=True)
    # Generate dummy npy
    np.save('exports/vortex_index_profile.npy', np.zeros((10,10)))
    print("🔧 Generating refractive index profile: exports/vortex_index_profile.npy")
    print("✓ Index profile saved: exports/vortex_index_profile.npy")

    lumerical_script = """# ARKHE Micro-Vortex Array - Lumerical FDTD Simulation
# Generated by ARKHE OS v∞.340.3

# === Simulation Setup ===
addfdtd;
set("name", "ARKHE_Vortex_Simulation");
set("x span", 12.0);  # μm
set("y span", 12.0);
set("z span", 5.0);
set("mesh accuracy", 3);

# === Material: PMMA with laser-induced index modulation ===
addmaterial("PMMA_laser_modified");
set("name", "PMMA_modified");
set("index", 1.49);

# === Vortex Array Geometry ===
n_profile_file = "/path/to/exports/vortex_index_profile.npy";
importnprofile(n_profile_file);

# === Source: Broadband plane wave ===
addplane;
set("name", "broadband_source");
set("wavelength start", 400);  # nm
set("wavelength stop", 1550);
set("theta", 0);
set("phi", 0);
set("injection axis", "z");

# === Monitors ===
addfarfield;
set("name", "farfield_spectrum");
set("monitor type", "far field");
set("wavelength start", 400);
set("wavelength stop", 1550);
set("wavelength points", 1151);

# === Execution ===
run;

# === Post-processing ===
lambda_axis = getdata("farfield_spectrum", "wavelength");
intensity = getdata("farfield_spectrum", "farfield3d");
spectral_response = mean(abs(intensity)^2, 3);
export("spectral_response.csv", lambda_axis', spectral_response');
"""
    with open('exports/vortex_array_lumerical.lsf', 'w') as f:
        f.write(lumerical_script)

    print("🔧 Generating Lumerical script: exports/vortex_array_lumerical.lsf")
    print("✓ Lumerical script saved: exports/vortex_array_lumerical.lsf")
    print("\n✅ Export to Lumerical complete")

if __name__ == '__main__':
    export()
